# Generated by Django 3.2.8 on 2021-12-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0001_initial'),
        ('messageManagement', '0001_initial'),
        ('caseManagement', '0002_case_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManagement.case'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.user'),
        ),
    ]
