# Generated by Django 3.2.8 on 2021-12-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_forgotpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
