# Generated by Django 3.2.8 on 2021-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=5000)),
                ('schedule_time', models.TimeField()),
                ('schedule_date', models.DateField()),
            ],
        ),
    ]
